services:
  app-service:
    build:
      context: ./app-service # specify directory where local Dockerfile is located
  auth-service:
    build:
      context: ./auth-service # specify directory where local Dockerfile is located
  nginx:
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
  certbot:
    profiles:
      - donotstart # this prevents the service from starting by default
