# Configuration for cargo-nextest
# See https://nexte.st/book/configuration.html for details

[profile.default]
# Set the number of parallel tests to 100
test-threads = 100

# You can also add other nextest configurations here if needed
# Example:
# retries = 2
# status-level = "fail"
# failure-output = "immediate"
# slow-timeout = { period = "60s", terminate-after = 3 }